
// example data model for chart api

[ {key: 'Year', value: '2010'}, {key: 'y1', value: '5'} ],
[ {key: 'Year', value: '2011'}, {key: 'y1', value: '10'} ],
[ {key: 'Year', value: '2012'}, {key: 'y1', value: '15'} ]

// example parsing function
var data = [];
function gatherData() {
    var query = connection.query("SELECT Yr, X1, X2 FROM randomData", function (err, res) {
        if (err) throw err; {
            console.log(res, "res");
            for (var i = 0; i < res.length; i++) {
                console.log(res[i].ID, "ayy")
                var year = res[i].Yr;
                var Y1 = res[i].X1;
                var Y2 = res[i].X2;
                console.log(year, "year")
                console.log(Y1, "Y1")
                console.log(Y2, "Y2")
                var entries = d3.entries(res[i])
                data.push(entries)
                console.log(entries, "What what")
                console.log(data, "data")
                var flatData = data.flat()
                console.log(flatData, "NERT NERT")
            }
        }
    });


    [
        {
          "dataId": 1,
          "name": "US Cheese Consumption",
          "description": "Per capita consumption of cheese (US)",
          "x_name": "Year",
          "y_name": "Pounds of Cheese",
          "DataValues": [ 
              { "id": 1, "dataId": 1, "x_value": 2000, "y_value": "29.80" },
            {
              "id": 2,
              "dataId": 1,
              "x_value": 2001,
              "y_value": "30.10"
            },
            {
              "id": 3,
              "dataId": 1,
              "x_value": 2002,
              "y_value": "30.50"
            },
            {
              "id": 4,
              "dataId": 1,
              "x_value": 2003,
              "y_value": "30.60"
            },
            {
              "id": 5,
              "dataId": 1,
              "x_value": 2004,
              "y_value": "31.30"
            },
            {
              "id": 6,
              "dataId": 1,
              "x_value": 2005,
              "y_value": "31.70"
            },
            {
              "id": 7,
              "dataId": 1,
              "x_value": 2006,
              "y_value": "32.60"
            },
            {
              "id": 8,
              "dataId": 1,
              "x_value": 2007,
              "y_value": "33.10"
            },
            {
              "id": 9,
              "dataId": 1,
              "x_value": 2008,
              "y_value": "32.70"
            },
            {
              "id": 10,
              "dataId": 1,
              "x_value": 2009,
              "y_value": "32.80"
            }
          ]
        },
        {
          "dataId": 2,
          "name": "US Golf Course Revenue",
          "description": "Total revenue generated by golf courses (US)",
          "x_name": "Year",
          "y_name": "Revenue",
          "DataValues": [
            {
              "id": 11,
              "dataId": 2,
              "x_value": 2000,
              "y_value": "16692.00"
            },
            {
              "id": 12,
              "dataId": 2,
              "x_value": 2001,
              "y_value": "16862.00"
            },
            {
              "id": 13,
              "dataId": 2,
              "x_value": 2002,
              "y_value": "17533.00"
            },
            {
              "id": 14,
              "dataId": 2,
              "x_value": 2003,
              "y_value": "17291.00"
            },
            {
              "id": 15,
              "dataId": 2,
              "x_value": 2004,
              "y_value": "18469.00"
            },
            {
              "id": 16,
              "dataId": 2,
              "x_value": 2005,
              "y_value": "19356.00"
            },
            {
              "id": 17,
              "dataId": 2,
              "x_value": 2006,
              "y_value": "20523.00"
            },
            {
              "id": 18,
              "dataId": 2,
              "x_value": 2007,
              "y_value": "21195.00"
            },
            {
              "id": 19,
              "dataId": 2,
              "x_value": 2008,
              "y_value": "21044.00"
            },
            {
              "id": 20,
              "dataId": 2,
              "x_value": 2009,
              "y_value": "20326.00"
            }
          ]
        }
      ]