
USE project2_db;

-- **** data set 1 ****
INSERT INTO data_names (data_id, `name`, `description`, x_name, y_name)
	VALUES (1, 'US Cheese Consumption', 'Per capita consumption of cheese (US)', 'Year', 'Pounds of Cheese');
INSERT INTO data_values (data_id, x_value, y_value)
	VALUES
		(1, 2000, 29.8),
		(1, 2001, 30.1),
		(1, 2002, 30.5),
		(1, 2003, 30.6),
		(1, 2004, 31.3),
		(1, 2005, 31.7),
		(1, 2006, 32.6),
		(1, 2007, 33.1),
		(1, 2008, 32.7),
		(1, 2009, 32.8)
;

-- **** data set 2 ****
INSERT INTO data_names (data_id, `name`, `description`, x_name, y_name)
	VALUES (2, 'US Golf Course Revenue', 'Total revenue generated by golf courses (US)', 'Year', 'Revenue');
INSERT INTO data_values (data_id, x_value, y_value)
	VALUES
		(2, 2000, 16692),
		(2, 2001, 16862),
		(2, 2002, 17533),
		(2, 2003, 17291),
		(2, 2004, 18469),
		(2, 2005, 19356),
		(2, 2006, 20523),
		(2, 2007, 21195),
		(2, 2008, 21044),
		(2, 2009, 20326)
;
